window.PORTFOLIO_OPS_DATA = {
  "project": {
    "name": "PortfolioOps",
    "version": "0.1.0",
    "generatedAt": "2026-03-30T14:01:48+00:00",
    "designBasis": [
      "Portfolio registry merged with live folder telemetry",
      "Triage recommendations and FAIR proxy scores folded into one readiness model",
      "Static GitHub Pages dashboard and E156 bundle"
    ]
  },
  "metrics": {
    "trackedProjects": 134,
    "meanReadiness": 59.7,
    "medianReadiness": 73,
    "resolvedStatusCount": 83,
    "resolvedStatusPercent": 61.9,
    "triageResolvedCount": 32,
    "triageResolvedPercent": 23.9,
    "codeSignalCount": 92,
    "codeSignalPercent": 68.7,
    "publishSignalCount": 80,
    "publishSignalPercent": 59.7,
    "operationallyBackedCount": 31,
    "operationallyBackedPercent": 23.1,
    "highReadinessCount": 74,
    "highReadinessPercent": 55.2
  },
  "actionBreakdown": [
    {
      "action": "Raise FAIR proxy maturity",
      "count": 37
    },
    {
      "action": "Monitor and maintain",
      "count": 31
    },
    {
      "action": "Freeze lifecycle status",
      "count": 28
    },
    {
      "action": "Fix indexed path",
      "count": 27
    },
    {
      "action": "Make Pages deliverable",
      "count": 6
    },
    {
      "action": "Initialize or repair git",
      "count": 3
    },
    {
      "action": "Complete manuscript bundle",
      "count": 2
    }
  ],
  "bestTiers": [
    {
      "tier": "Tier 2",
      "meanReadiness": 87.0,
      "count": 8
    },
    {
      "tier": "Tier 1",
      "meanReadiness": 86.0,
      "count": 7
    },
    {
      "tier": "Tier 7",
      "meanReadiness": 85.7,
      "count": 6
    },
    {
      "tier": "Tier 3",
      "meanReadiness": 83.3,
      "count": 6
    },
    {
      "tier": "Tier 4",
      "meanReadiness": 83.2,
      "count": 20
    },
    {
      "tier": "Tier 5",
      "meanReadiness": 77.3,
      "count": 7
    }
  ],
  "weakestTiers": [
    {
      "tier": "Tier 12",
      "meanReadiness": 12.3,
      "count": 26
    },
    {
      "tier": "Tier 8",
      "meanReadiness": 41.7,
      "count": 3
    },
    {
      "tier": "Tier 11",
      "meanReadiness": 46.4,
      "count": 5
    },
    {
      "tier": "Tier 9",
      "meanReadiness": 57.6,
      "count": 5
    },
    {
      "tier": "Tier 10",
      "meanReadiness": 61.1,
      "count": 33
    },
    {
      "tier": "Tier 6",
      "meanReadiness": 62.8,
      "count": 8
    }
  ],
  "topProjects": [
    {
      "name": "HTA Artifact Standard",
      "id": "11",
      "path": "C:\\HTML apps\\HTA\\",
      "tier": "Tier 2",
      "tierName": "Tier 2 \u2014 HTML Apps Portfolio",
      "type": "HTML app",
      "explicitStatus": "Shipped",
      "resolvedStatus": "Shipped",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 90,
      "fairBand": "strong",
      "readinessScore": 96,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 36/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "AdaptSim",
      "id": "6",
      "path": "C:\\AdaptSim\\",
      "tier": "Tier 1",
      "tierName": "Tier 1 \u2014 Flagship Projects (active or near-submission)",
      "type": "HTML app",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 6,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "Al-Mizan",
      "id": "4",
      "path": "C:\\AlMizan\\",
      "tier": "Tier 1",
      "tierName": "Tier 1 \u2014 Flagship Projects (active or near-submission)",
      "type": "HTML app",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 6,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "Clinic Website",
      "id": "7",
      "path": "C:\\Projects\\clinic-site\\",
      "tier": "Tier 1",
      "tierName": "Tier 1 \u2014 Flagship Projects (active or near-submission)",
      "type": "Static site",
      "explicitStatus": "Shipped",
      "resolvedStatus": "Shipped",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 6,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "HTA Transportability",
      "id": "50",
      "path": "C:\\Models\\HTA_Transportability_Engine\\",
      "tier": "Tier 7",
      "tierName": "Tier 7 \u2014 HTA Suite",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "IPD-Meta-Pro",
      "id": "9",
      "path": "C:\\HTML apps\\IPD-Meta-Pro\\",
      "tier": "Tier 2",
      "tierName": "Tier 2 \u2014 HTML Apps Portfolio",
      "type": "HTML app",
      "explicitStatus": "Shipped",
      "resolvedStatus": "Shipped",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 7,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "Value-Based HTA",
      "id": "51",
      "path": "C:\\Models\\Value_Based_HTA_Engine\\",
      "tier": "Tier 7",
      "tierName": "Tier 7 \u2014 HTA Suite",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "DTA Pro",
      "id": "10",
      "path": "C:\\HTML apps\\DTA_Pro_Review\\",
      "tier": "Tier 2",
      "tierName": "Tier 2 \u2014 HTML Apps Portfolio",
      "type": "HTML app",
      "explicitStatus": "Archived",
      "resolvedStatus": "Archived",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 75,
      "fairBand": "emerging",
      "readinessScore": 90,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 7,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 30/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "HTA Evidence Integrity",
      "id": "49",
      "path": "C:\\Models\\HTA_Evidence_Integrity_Suite\\",
      "tier": "Tier 7",
      "tierName": "Tier 7 \u2014 HTA Suite",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 75,
      "fairBand": "emerging",
      "readinessScore": 90,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 30/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "CRES",
      "id": "24",
      "path": "C:\\Models\\CRES\\",
      "tier": "Tier 4",
      "tierName": "Tier 4 \u2014 R Packages & Methods Papers",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 70,
      "fairBand": "emerging",
      "readinessScore": 88,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 28/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "GWAM",
      "id": "26",
      "path": "C:\\Models\\GWAM\\",
      "tier": "Tier 4",
      "tierName": "Tier 4 \u2014 R Packages & Methods Papers",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 70,
      "fairBand": "emerging",
      "readinessScore": 88,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 28/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "HeterogeneityASE",
      "id": "22",
      "path": "C:\\Models\\New_Heterogeneity_Model\\",
      "tier": "Tier 4",
      "tierName": "Tier 4 \u2014 R Packages & Methods Papers",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 70,
      "fairBand": "emerging",
      "readinessScore": 88,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 28/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    }
  ],
  "backedProjects": [
    {
      "name": "HTA Artifact Standard",
      "id": "11",
      "path": "C:\\HTML apps\\HTA\\",
      "tier": "Tier 2",
      "tierName": "Tier 2 \u2014 HTML Apps Portfolio",
      "type": "HTML app",
      "explicitStatus": "Shipped",
      "resolvedStatus": "Shipped",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 90,
      "fairBand": "strong",
      "readinessScore": 96,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 36/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "AdaptSim",
      "id": "6",
      "path": "C:\\AdaptSim\\",
      "tier": "Tier 1",
      "tierName": "Tier 1 \u2014 Flagship Projects (active or near-submission)",
      "type": "HTML app",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 6,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "Al-Mizan",
      "id": "4",
      "path": "C:\\AlMizan\\",
      "tier": "Tier 1",
      "tierName": "Tier 1 \u2014 Flagship Projects (active or near-submission)",
      "type": "HTML app",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 6,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "Clinic Website",
      "id": "7",
      "path": "C:\\Projects\\clinic-site\\",
      "tier": "Tier 1",
      "tierName": "Tier 1 \u2014 Flagship Projects (active or near-submission)",
      "type": "Static site",
      "explicitStatus": "Shipped",
      "resolvedStatus": "Shipped",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 6,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "HTA Transportability",
      "id": "50",
      "path": "C:\\Models\\HTA_Transportability_Engine\\",
      "tier": "Tier 7",
      "tierName": "Tier 7 \u2014 HTA Suite",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "IPD-Meta-Pro",
      "id": "9",
      "path": "C:\\HTML apps\\IPD-Meta-Pro\\",
      "tier": "Tier 2",
      "tierName": "Tier 2 \u2014 HTML Apps Portfolio",
      "type": "HTML app",
      "explicitStatus": "Shipped",
      "resolvedStatus": "Shipped",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 7,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "Value-Based HTA",
      "id": "51",
      "path": "C:\\Models\\Value_Based_HTA_Engine\\",
      "tier": "Tier 7",
      "tierName": "Tier 7 \u2014 HTA Suite",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 80,
      "fairBand": "strong",
      "readinessScore": 92,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 32/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "DTA Pro",
      "id": "10",
      "path": "C:\\HTML apps\\DTA_Pro_Review\\",
      "tier": "Tier 2",
      "tierName": "Tier 2 \u2014 HTML Apps Portfolio",
      "type": "HTML app",
      "explicitStatus": "Archived",
      "resolvedStatus": "Archived",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 75,
      "fairBand": "emerging",
      "readinessScore": 90,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 7,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 30/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "HTA Evidence Integrity",
      "id": "49",
      "path": "C:\\Models\\HTA_Evidence_Integrity_Suite\\",
      "tier": "Tier 7",
      "tierName": "Tier 7 \u2014 HTA Suite",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 75,
      "fairBand": "emerging",
      "readinessScore": 90,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 30/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "CRES",
      "id": "24",
      "path": "C:\\Models\\CRES\\",
      "tier": "Tier 4",
      "tierName": "Tier 4 \u2014 R Packages & Methods Papers",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 70,
      "fairBand": "emerging",
      "readinessScore": 88,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 28/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "GWAM",
      "id": "26",
      "path": "C:\\Models\\GWAM\\",
      "tier": "Tier 4",
      "tierName": "Tier 4 \u2014 R Packages & Methods Papers",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 70,
      "fairBand": "emerging",
      "readinessScore": 88,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 28/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    },
    {
      "name": "HeterogeneityASE",
      "id": "22",
      "path": "C:\\Models\\New_Heterogeneity_Model\\",
      "tier": "Tier 4",
      "tierName": "Tier 4 \u2014 R Packages & Methods Papers",
      "type": "Model",
      "explicitStatus": "Submission ready",
      "resolvedStatus": "Submission ready",
      "statusResolved": true,
      "resolutionSource": "explicit",
      "triageLabel": "",
      "triageConfidence": "",
      "fairTotal": 70,
      "fairBand": "emerging",
      "readinessScore": 88,
      "hasLivePath": true,
      "hasGit": true,
      "gitDirty": false,
      "hasTests": true,
      "hasPaper": true,
      "hasProtocol": true,
      "pagesReady": true,
      "activityBand": "fresh",
      "operationalSignals": 8,
      "publishSignal": true,
      "codeSignal": true,
      "operationallyBacked": true,
      "primaryAction": "Monitor and maintain",
      "reasons": [
        "FAIR proxy contributes 28/40",
        "Explicit lifecycle label present (+12)",
        "Specific live path exists (+8)",
        "Git repository detected (+8)",
        "Git worktree appears clean (+4)",
        "Tests marker detected (+6)",
        "Paper artifact detected (+6)",
        "Protocol artifact detected (+6)"
      ]
    }
  ],
  "priorityQueue": [
    {
      "name": "MAFI",
      "id": "88",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "MAFI-Continuation",
      "id": "89",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "MLM501",
      "id": "87",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "MetaFusion-Lab",
      "id": "100",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "Multipledatameta",
      "id": "103",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "advanced-nma-pooling",
      "id": "97",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "claude-plugins",
      "id": "102",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "claude-rct-work",
      "id": "101",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "esc-acs-living-meta",
      "id": "85",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "evidence-inference",
      "id": "80",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "glm-code",
      "id": "104",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "hfpef_registry_calibration",
      "id": "83",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "hfpef_registry_synth",
      "id": "82",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "idea12",
      "id": "92",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "ipd-meta-pro-link",
      "id": "94",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    },
    {
      "name": "ipd_qma_project",
      "id": "95",
      "path": "C:\\Projects\\",
      "tier": "Tier 12",
      "tierName": "Tier 12 \u2014 Research Projects (C:\\Projects\\, various)",
      "type": "Project",
      "explicitStatus": "Needs triage",
      "resolvedStatus": "Needs triage",
      "statusResolved": false,
      "resolutionSource": "unresolved",
      "triageLabel": "Needs triage",
      "triageConfidence": "low",
      "fairTotal": 25,
      "fairBand": "weak",
      "readinessScore": 10,
      "hasLivePath": false,
      "hasGit": false,
      "gitDirty": false,
      "hasTests": false,
      "hasPaper": false,
      "hasProtocol": false,
      "pagesReady": false,
      "activityBand": "generic",
      "operationalSignals": 0,
      "publishSignal": false,
      "codeSignal": false,
      "operationallyBacked": false,
      "primaryAction": "Fix indexed path",
      "reasons": [
        "FAIR proxy contributes 10/40"
      ]
    }
  ]
};
